#set up properties
PROJECT_ID: qwiklabs-gcp-00-96ff96e16985

server:
    port: ${DEFAULT_PORT:80}

spring:
    application:
        name: app-bigquery
    cloud:
        config:
            namespace: default
            enabled: true
            name: Cloud
            profile: dev, cloud, bigquery
            label: master
        gcp:
            project-id: ${PROJECT_ID:qwiklabs-gcp-00-96ff96e16985}
            credentials:
                location: classpath:key.json  
            bigquery:
                datasetName: ${DATASET_NAME:marketplace}  